### ISSUE TITLE
Show invoice on reverse swap send screen

### ISSUE THREAD

**Issue by michael1011** [BoltzExchange/boltz-web-app#244]
In a sensible way. Eg the human readable part of the beginning and a couple letters of the end

**Comment by armurbalda** [comment]
What does this help with when only showing beginning and end? That the copy button did indeed copy the correct invoice?

I'd rather than show it in it's entirety for the folks who like "select all & copy" over a copy button.

![image](https://github.com/BoltzExchange/boltz-web-app/assets/16877539/1ff9033c-8eee-46a9-b4d7-7e42952e9d12)

**Comment by michael1011** [comment]
> What does this help with when only showing beginning and end? That the copy button did indeed copy the correct invoice?

Allow detecting clipboard injections, yes
