### ISSUE TITLE
Add Branding, Youtube Link 

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#445]
- Branding: https://github.com/BoltzExchange/logo
- Youtube: https://www.youtube.com/@boltzhq

We should also consider a footer menu once we have a couple of more 2nd prio menu items that we can't fit anywhere else

![image](https://github.com/BoltzExchange/boltz-web-app/assets/19181985/6d21dc20-714a-4bb6-94a6-37c5c2c2b7c4)

**Comment by dni** [comment]
i think it would work if we but the status in the main navbar, there is still enough room there and also i think the status page is pretty invisible for its importance now.

put youtube instead of the betterstack logo

and put the branding stuff into docs in the resources section, because i dont think it that important to be on the main page.

![screenshot-1707659087](https://github.com/BoltzExchange/boltz-web-app/assets/1743657/6667dd5b-df4e-4283-b43c-c9d327fdce35)

if possible i would love to keep our footer as clean as possible, but i understand that its is getting crowded.
